f_name = input("First name: ")
l_name = input("Last name: ")
email = input("Email address: ")
phone = input("Phone number: ")
job = input("Job title: ")
id_num = input("ID number: ")
hair_color = input("Hair color: ")
eye_color = input("Eye color: ")
started  = input("Started working on: ")
training = input("Training completed: ")

print("The ID Card is:")

print("--------------------------------------")
print(f"{l_name.upper()}, {f_name}")
print(job.title())
print(f"ID: {id_num}")
print()
print(email.lower())
print(phone)
print()
print("Hair Color: {0:20} Eye Color {1}".format(hair_color, eye_color))
print("Started On: {0:20} Training Completed: {1}".format(started, training))
print("--------------------------------------")